name = "securesoulscom"
main = "build/index.js"
compatibility_date = "2026-09-22"

[build]
command = "cd worker && cargo install -q \"worker-build@^0.8\" && worker-build --release"

[observability.logs]
enabled = true
head_sampling_rate = 1
invocation_logs = true
persist = true

[observability.traces]
enabled = true
head_sampling_rate = 1
persist = true